# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46485093e97e6e0b1e01a2d925a3c965eda0d3028da02590545274d7a65afc5d89d67d1a680d92fce0d80f19daa71be3ae339e3deefe7c5e198fd4009e850e2c

test:
  secret_key_base: 56d7b19a74b2bbf717ee45a0f847bd5976e2b567ffe6fa6d0bcec95a97876ef7ec19a685d8fef0229a89304c3e273afad6e6c72bbcf22c7db95680054b98e7c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
